apiVersion: apps/v1
kind: Deployment
metadata:
  name: project2-deployment  
spec:  
  replicas: 3
  selector:
    matchLabels:
      app: project2-app
  template:
    metadata:
      labels:
        app: project2-app
    spec:
      containers:
      - name: project2-container
        image: jorgemongelos/project2:v1.2 
        # imagePullPolicy: Never
        # restartPolicy: never
        ports:
        - containerPort: 8080
        env:
          - name: DB_URL
            value: jdbc:postgresql://postgres-service:5432/postgres
          - name: DB_USER
            value: postgres
#kubectl create secret generic demo-credentials \
# --from-literal=username=postgres \
# --from-literal=...=... \
            # valueFrom:
            #   secretKeyRef:
            #     key: username
            #     name: demo-credentials
            #     optional: false
          - name: DB_PASS
            value: pass
          # could add an env var for spring profile value: prod

 