server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:mem:dbtest
    username: sa
    password: p4ss
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  h2:
   console:
    enabled: true
